// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: dreamwaver/v1/sandbox.proto

package dreamwaverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_LANGUAGE_UNSPECIFIED Language = 0
	Language_LANGUAGE_PYTHON      Language = 1
	Language_LANGUAGE_NODE        Language = 2
	Language_LANGUAGE_BASH        Language = 3
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "LANGUAGE_UNSPECIFIED",
		1: "LANGUAGE_PYTHON",
		2: "LANGUAGE_NODE",
		3: "LANGUAGE_BASH",
	}
	Language_value = map[string]int32{
		"LANGUAGE_UNSPECIFIED": 0,
		"LANGUAGE_PYTHON":      1,
		"LANGUAGE_NODE":        2,
		"LANGUAGE_BASH":        3,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_dreamwaver_v1_sandbox_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_dreamwaver_v1_sandbox_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_dreamwaver_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Programming language to interpret `code` with.
	Language Language `protobuf:"varint,1,opt,name=language,proto3,enum=dreamwaver.v1.Language" json:"language,omitempty"`
	// Source code to execute.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Optional stdin payload.
	Stdin string `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	// Hard timeout in milliseconds. Default 30000.
	TimeoutMs uint32 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Memory limit in MB. Default 256.
	MemoryMb uint32 `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	// Environment variables (key=value).
	Env []string `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty"`
	// Files to mount into the sandbox (path → contents).
	Files         map[string][]byte `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_dreamwaver_v1_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamwaver_v1_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_dreamwaver_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *ExecuteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteRequest) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *ExecuteRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecuteRequest) GetMemoryMb() uint32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ExecuteRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetFiles() map[string][]byte {
	if x != nil {
		return x.Files
	}
	return nil
}

type ExecuteResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Stdout   string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr   string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Wall-clock duration in milliseconds.
	DurationMs uint64 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Files produced by the sandbox (path → contents).
	OutputFiles map[string][]byte `protobuf:"bytes,5,rep,name=output_files,json=outputFiles,proto3" json:"output_files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Set when the runtime itself errored (OOM, timeout, etc.).
	RuntimeError  string `protobuf:"bytes,6,opt,name=runtime_error,json=runtimeError,proto3" json:"runtime_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_dreamwaver_v1_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dreamwaver_v1_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_dreamwaver_v1_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetDurationMs() uint64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecuteResponse) GetOutputFiles() map[string][]byte {
	if x != nil {
		return x.OutputFiles
	}
	return nil
}

func (x *ExecuteResponse) GetRuntimeError() string {
	if x != nil {
		return x.RuntimeError
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_dreamwaver_v1_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamwaver_v1_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_dreamwaver_v1_sandbox_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_dreamwaver_v1_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dreamwaver_v1_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_dreamwaver_v1_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_dreamwaver_v1_sandbox_proto protoreflect.FileDescriptor

const file_dreamwaver_v1_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x1bdreamwaver/v1/sandbox.proto\x12\rdreamwaver.v1\"\xb7\x02\n" +
	"\x0eExecuteRequest\x123\n" +
	"\blanguage\x18\x01 \x01(\x0e2\x17.dreamwaver.v1.LanguageR\blanguage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05stdin\x18\x03 \x01(\tR\x05stdin\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\rR\ttimeoutMs\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\rR\bmemoryMb\x12\x10\n" +
	"\x03env\x18\x06 \x03(\tR\x03env\x12>\n" +
	"\x05files\x18\a \x03(\v2(.dreamwaver.v1.ExecuteRequest.FilesEntryR\x05files\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xb8\x02\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x04R\n" +
	"durationMs\x12R\n" +
	"\foutput_files\x18\x05 \x03(\v2/.dreamwaver.v1.ExecuteResponse.OutputFilesEntryR\voutputFiles\x12#\n" +
	"\rruntime_error\x18\x06 \x01(\tR\fruntimeError\x1a>\n" +
	"\x10OutputFilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\":\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion*_\n" +
	"\bLanguage\x12\x18\n" +
	"\x14LANGUAGE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLANGUAGE_PYTHON\x10\x01\x12\x11\n" +
	"\rLANGUAGE_NODE\x10\x02\x12\x11\n" +
	"\rLANGUAGE_BASH\x10\x032\x9a\x01\n" +
	"\aSandbox\x12H\n" +
	"\aExecute\x12\x1d.dreamwaver.v1.ExecuteRequest\x1a\x1e.dreamwaver.v1.ExecuteResponse\x12E\n" +
	"\x06Health\x12\x1c.dreamwaver.v1.HealthRequest\x1a\x1d.dreamwaver.v1.HealthResponseB^Z\\github.com/dreamwaver/dreamwaver/services/orchestrator/internal/pb/dreamwaverv1;dreamwaverv1b\x06proto3"

var (
	file_dreamwaver_v1_sandbox_proto_rawDescOnce sync.Once
	file_dreamwaver_v1_sandbox_proto_rawDescData []byte
)

func file_dreamwaver_v1_sandbox_proto_rawDescGZIP() []byte {
	file_dreamwaver_v1_sandbox_proto_rawDescOnce.Do(func() {
		file_dreamwaver_v1_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dreamwaver_v1_sandbox_proto_rawDesc), len(file_dreamwaver_v1_sandbox_proto_rawDesc)))
	})
	return file_dreamwaver_v1_sandbox_proto_rawDescData
}

var file_dreamwaver_v1_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dreamwaver_v1_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dreamwaver_v1_sandbox_proto_goTypes = []any{
	(Language)(0),           // 0: dreamwaver.v1.Language
	(*ExecuteRequest)(nil),  // 1: dreamwaver.v1.ExecuteRequest
	(*ExecuteResponse)(nil), // 2: dreamwaver.v1.ExecuteResponse
	(*HealthRequest)(nil),   // 3: dreamwaver.v1.HealthRequest
	(*HealthResponse)(nil),  // 4: dreamwaver.v1.HealthResponse
	nil,                     // 5: dreamwaver.v1.ExecuteRequest.FilesEntry
	nil,                     // 6: dreamwaver.v1.ExecuteResponse.OutputFilesEntry
}
var file_dreamwaver_v1_sandbox_proto_depIdxs = []int32{
	0, // 0: dreamwaver.v1.ExecuteRequest.language:type_name -> dreamwaver.v1.Language
	5, // 1: dreamwaver.v1.ExecuteRequest.files:type_name -> dreamwaver.v1.ExecuteRequest.FilesEntry
	6, // 2: dreamwaver.v1.ExecuteResponse.output_files:type_name -> dreamwaver.v1.ExecuteResponse.OutputFilesEntry
	1, // 3: dreamwaver.v1.Sandbox.Execute:input_type -> dreamwaver.v1.ExecuteRequest
	3, // 4: dreamwaver.v1.Sandbox.Health:input_type -> dreamwaver.v1.HealthRequest
	2, // 5: dreamwaver.v1.Sandbox.Execute:output_type -> dreamwaver.v1.ExecuteResponse
	4, // 6: dreamwaver.v1.Sandbox.Health:output_type -> dreamwaver.v1.HealthResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dreamwaver_v1_sandbox_proto_init() }
func file_dreamwaver_v1_sandbox_proto_init() {
	if File_dreamwaver_v1_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dreamwaver_v1_sandbox_proto_rawDesc), len(file_dreamwaver_v1_sandbox_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dreamwaver_v1_sandbox_proto_goTypes,
		DependencyIndexes: file_dreamwaver_v1_sandbox_proto_depIdxs,
		EnumInfos:         file_dreamwaver_v1_sandbox_proto_enumTypes,
		MessageInfos:      file_dreamwaver_v1_sandbox_proto_msgTypes,
	}.Build()
	File_dreamwaver_v1_sandbox_proto = out.File
	file_dreamwaver_v1_sandbox_proto_goTypes = nil
	file_dreamwaver_v1_sandbox_proto_depIdxs = nil
}
